[workspace]
members=[
  "auction/program",
  "auction-house/program",
  "gumdrop/program",
  "metaplex/program",
  "token-entangler/program",
  "token-vault/program",
  "token-vault/test",
  "nft-packs/program",
  "fixed-price-sale/program",
  "stealth/program",
  "stealth/escrow",
  "stealth/cli",
  "stealth/js/native",
]
exclude = [
  "fixed-price-sale/cli",
  "token-metadata",
  "candy-machine/program"
]
