[workspace]
members=[
  "auction/program",
  "metaplex/program",
  "token-vault/program",
  "token-vault/test",
  "token-metadata/program",
  "token-metadata/test",
  "private-metadata/program",
  "private-metadata/cli",
  "private-metadata/js/native",
]
exclude = []
